title: Lyons Grey Cat
description: "A collection of cybersecurity write-ups and challenges solved, including Hack The Box, TryHackMe, and more."
theme: just-the-docs

url: https://lyonspeed.github.io

collections_dir: collections


collections:
  collections/hacme:
    permalink: "/:collection/:path/"
    output: true



just_the_docs:
  title_separator: " "
  home_page_title: "Lyons Grey Cat"


  collections:
    collections/hacme:
      name: Hackme
      nav_exclude: false  # Incluir en la navegación (por defecto)
      search_exclude: false  # Incluir en la búsqueda (por defecto)
      nav_fold: true  # Plegar la colección en la navegación (nuevo en v0.4)






#aux_links:
#  Template Repository: https://github.com/just-the-docs/just-the-docs-template
